[package]
name = "discord_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
dotenv = "0.15"
lazy_static = "1.4"
reqwest = { version = "0.11", features = ["json"] }
rand = "0.8.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
